### ISSUE TITLE
Add Table Functionality is broken 

### ISSUE THREAD

**Issue by emirhantandogan** [ChagataiDuru/CS320-Term-Project-ProCafeOnline#4]
@ChagataiDuru 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\Users\DELL\Desktop\PCO\PCO\view\main_page.py", line 99, in <lambda>
    submit_button = ttk.Button(new_window, text="Add Table", style='TButton', command=lambda: save_table(name_entry.get(), type_entry.get(), fee_entry.get(), image_path_label.cget("text"), new_window, table_tree))
  File "c:\Users\DELL\Desktop\PCO\PCO\controller\main_page_controller.py", line 44, in save_table
    update_treeview(table_tree)
  File "c:\Users\DELL\Desktop\PCO\PCO\controller\main_page_controller.py", line 57, in update_treeview
    for table in Table.get_all_tables():
  File "c:\Users\DELL\Desktop\PCO\PCO\model\table.py", line 44, in get_all_tables
    table_obj = Table(name=tbl[0], duration=tbl[1], type=tbl[2], open_close=tbl[3], feePerMinute=tbl[4], fee=tbl[5], feeFromDuration=tbl[6], feeFromCafe=tbl[7], image_path=tbl[8])
IndexError: tuple index out of range

**Comment by ChagataiDuru** [comment]
Issue fixed
